### PR TITLE
[PE-D Bugs] Update parsing and input error detection of AddCommand

### LINKED ISSUE #137: [PE-D][Tester D] Generic add command error message
Generic add command error message

Image

I think from the image above, it can be seen that it is quite frustrating to figure out what exactly is wrong with my input because some of the inputs seem to be correct, yet all of them throw the same generic message
```
Invalid add command.
Usage: add company/COMPANY_NAME role/ROLE_NAME deadline/DEADLINE pay/PAY_AMOUNT
```

Would be nice if you could mention which part of the input is wrong!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #144: [PE-D][Tester A] Feature: add command gives unhelpful error messages when parsing fields
### Description
When using the `add` command with incorrect or missing fields, the program only shows a generic error message.  
It does not specify which field caused the problem, making it difficult for users to identify and correct their input.

### Steps to Reproduce

1. Launch the application.

2. Enter an invalid add command, e.g. add company/google

3. Observe the error message.

Invalid add command.
Usage: add company/COMPANY_NAME role/ROLE_NAME deadline/DEADLINE pay/PAY_AMOUNT

### Suggested Fix
Improve the parser’s field validation logic to provide specific feedback, e.g.:
- `Missing required field: deadline/`
- `Invalid field format: deadline/ expected dd-MM-yyyy (e.g. 08-10-2025)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #164: [PE-D][Tester E] App rejects valid add command format
1. Open the app using: java -jar "Internity.jar"
2. Type this command:
   add company/Google role/Intern deadline/12/12/2025 pay/1000
3. Press Enter.

Expected:
The app should add the internship entry and confirm it was added.

Actual:
It says "Invalid add command" even though the command follows the format shown in the usage message.

Severity: High  
Type: FunctionalityBug

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #165: [PE-D][Tester E] ejects valid add command format
1. Type: add company/Google role/Intern deadline/32/12/2025 pay/1000
2. Press Enter.

Expected:
App should show one clear message like "Invalid date format."

Actual:
It shows two messages: 
"Invalid add command" and "Invalid date format or impossible date."

Severity: Low  
Type: FeatureFlaw

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #166: [PE-D][Tester E] add command with normal syntax
1. Run the app.
2. Type: add Google Intern /by 12/12/2025 /pay 1000
3. Press Enter.

Expected:
The internship should be added.

Actual:
App says "Invalid add command."  
This format is similar to what most users expect, but it is not accepted.

Severity: Medium  
Type: FunctionalityBug

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #167: [PE-D][Tester E] Confusing error message
1. Run the app.
2. Type: add /by 12/12/2025 /pay 1500

Expected:
App should show a message explaining which part is missing (like company or role).

Actual:
App only says "Invalid add command" without explaining what is wrong.

Severity: Low  
Type: FeatureFlaw

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #169: [PE-D][Tester E] add accepts only one date format
1. Run the app.  
2. Try these such commands:
   - add company/Microsoft role/Backend Intern deadline/15-11-2025 pay/1500   
   - add company/Apple role/Frontend Intern deadline/15/11/2025 pay/1500     
   - add company/Apple role/Frontend Intern deadline/2025-11-15 pay/1500     
   - add company/Apple role/Frontend Intern deadline/15 Nov 2025 pay/1500    
   - add company/Meta role/AI Intern deadline/11/11/25 pay/1000          
Expected:
Either accept common date formats (documented), or show a clear message that only dd-MM-yyyy is supported.

Actual:
Only dd-MM-yyyy works; others fail with a generic "Invalid add command".

Severity: Medium
Type: FeatureFlaw

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #172: [PE-D][Tester E] Generic add error message hides what’s wrong
1. Run: add company/Google role/Intern deadline/12/12/2025
   (missing pay field)

Expected:
A specific message telling which field is missing (e.g., "Missing pay/ amount").

Actual:
Only "Invalid add command" is shown, without explaining which part is missing.

Severity: Low
Type: FeatureFlaw

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #174: Add command bugs

### PR DESCRIPTION
**Pull request by BestBearrr**
This PR updates the parsing and input error detection of AddCommand, resolving the following PE-D bugs.

Closes #174
---
Closes #137
Closes #144
Closes #164
Closes #165 
Closes #166
Closes #167
Closes #169
Closes #172

### CODE REVIEW

File: src/main/java/internity/logic/cli/ArgumentParser.java [hunk 1]
```diff
@@ -34,7 +34,8 @@ public final class ArgumentParser {
     private static final int IDX_ROLE = 1;
     private static final int IDX_DEADLINE = 2;
     private static final int IDX_PAY = 3;
-    private static final String ADD_COMMAND_PARSE_LOGIC = "\\s+(?=company/|role/|deadline/|pay/)";
+    private static final String PARSE_LOGIC_ADD = "\\s+(?=company/|role/|deadline/|pay/)";
+    private static final String PARSE_LOGIC_UPDATE = "\\s+(?=company/|role/|deadline/|pay/|status/)";
```
Comment (V1T0bh) [inline src/main/java/internity/logic/cli/ArgumentParser.java]: Using constants for readability. Good call.

File: text-ui-test/input.txt
Comment (V1T0bh) [inline text-ui-test/input.txt]: try adding a check if a pay > MAXINT is given. see if expected output is given.

File: src/main/java/internity/logic/cli/ArgumentParser.java [hunk 2]
```diff
@@ -322,7 +365,7 @@ private static String[] splitIndexAndTagged(String trimmed) throws InternityExce
         }
         String indexToken = trimmed.substring(0, firstSpace).trim();
         String tagged = trimmed.substring(firstSpace + 1).trim();
-        return new String[] { indexToken, tagged };
+        return new String[]{indexToken, tagged};
```
[the remark this answers is not in the document]
Comment (BestBearrr) [reply src/main/java/internity/logic/cli/ArgumentParser.java]: Thanks, somehow the auto-format made it this way instead.

File: src/main/java/internity/ui/Ui.java [hunk 3]
```diff
@@ -77,14 +77,15 @@ public static void printExit() {
      *
      * @param internship the internship that was added
      */
-    public static void printAddInternship(Internship internship) {
-        System.out.println("Noted. I've added this internship:");
+    public static void printAddInternship(Internship internship, int totalItems) {
```
[the remark this answers is not in the document]
Comment (BestBearrr) [reply src/main/java/internity/ui/Ui.java]: Updated

File: src/main/java/internity/core/InternityException.java [hunk 4]
```diff
@@ -175,7 +175,7 @@ public static InternityException invalidIndexForUpdate() {
      * @return an {@code InternityException} for an invalid pay format
      */
     public static InternityException invalidPayFormat() {
-        return new InternityException("Invalid pay. Must be a non-negative integer. (Example: pay/8000)");
+        return new InternityException("Invalid pay. Must be a non-negative integer and within the allowed range. (Example: pay/8000)");
```
Comment (V1T0bh) [inline src/main/java/internity/core/InternityException.java]: good fix :)
