### PR TITLE
fix input constraints bug 

### LINKED ISSUE #100: fix bug where character limit doesnt apply to update command
Previously, character limits were added to the input fields for Add command. The Update command remained unaffected.

Fix the problem where the Update command is not affected by character limit (defined in InternshipList).

### PR DESCRIPTION
**Pull request by V1T0bh**
This pull request improves validation and error handling for field length constraints in the add and update command argument parsing logic. Instead of using a generic error, the code now throws more specific exceptions with detailed messages when the company or role fields exceed their maximum allowed lengths. Additionally, new exception helper methods have been added to centralize and clarify these error messages.

**Validation and error handling improvements:**

* [`src/main/java/internity/logic/cli/ArgumentParser.java`](diffhunk://#diff-2c4efe9704e566f52146e091790f92f07cadc881213f3bd039f5e060654ccbacL74-R80): Replaced the generic length-exceeding error for `company` and `role` fields in both add and update commands with specific checks that throw a new, descriptive exception when the maximum length is exceeded. Logging has also been improved for these cases. [[1]](diffhunk://#diff-2c4efe9704e566f52146e091790f92f07cadc881213f3bd039f5e060654ccbacL74-R80) [[2]](diffhunk://#diff-2c4efe9704e566f52146e091790f92f07cadc881213f3bd039f5e060654ccbacR156-R172)

**Exception utility enhancements:**

* [`src/main/java/internity/core/InternityException.java`](diffhunk://#diff-1006130f5a8a29f31668d326a3e7d43e5bcb9370e5de5a9e5000c47888fd9761R65-R72): Added new static methods `exceedFieldLength` and `exceedFieldValue` to generate more informative exceptions when a field exceeds its allowed length or value, making error handling more consistent and user-friendly.

closes #100

### CODE REVIEW

File: src/main/java/internity/logic/cli/ArgumentParser.java [hunk 1]
```diff
@@ -121,10 +121,13 @@ public static AddCommand parseAddCommandArgs(String args) throws InternityExcept
...
-                logger.severe("One or more arguments exceeded max length.");
-                throw InternityException.invalidAddCommand();
+            if (company.length() > InternshipList.COMPANY_MAXLEN) {
+                logger.severe("Company name exceeded max length.");
+                throw InternityException.exceedFieldLength("Company", InternshipList.COMPANY_MAXLEN, company.length());
+            }
+            if (role.length() > InternshipList.ROLE_MAXLEN) {
+                logger.severe("Role exceeded max length.");
+                throw InternityException.exceedFieldLength("Role", InternshipList.ROLE_MAXLEN, role.length());
             }
```
Comment (lukeai-tan) [inline src/main/java/internity/logic/cli/ArgumentParser.java]: Good job splitting up for the more concise exception messages.
