### PR TITLE
fix issues raised by PED

### LINKED ISSUE #134: [PE-D][Tester D] When updating an internship, it always says internship status updated, even when other things are being updated.
When updating an internship, it always says internship status updated, even when other things are being updated.

Image

In the image above, company is being updated, but it still says status is being updated, maybe can change the word to internship updated successfully?

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #135: [PE-D][Tester D] The find index does not match the list index
The find index does not match the list index

Image

This could cause issues when other functions that utilise index is required, and I have a huge list of internships, but when I try to find an internship in this huge list, I am unable to scroll through and find them, but when I use the find method, I cannot get the index, so I still cannot access that internship and update/delete it.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #152: [PE-D][Tester C] Dashboard shows internship that's overdued as nearest deadline
The dashboard shows internship that's overdued as the nearest deadline, which is misleading. Nearest deadline is more for internships that are going to expire soon. Perhaps you can change the type of internship displayed for the nearest deadline, or rename it to overdued internships so that it's more clear.

Steps to reproduce:
1. add an overdued internship e.g. `add company/nets role/intern deadline/10-10-1999 pay/15000`
2. enter the command `dashboard`

Below is a screenshot of the bug:

Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #153: [PE-D][Tester C] Description for update command in the help command is incomplete
The description for the update command in the help command display is incomplete. It only shows that the user can use it to update the status of the internship, but the update command can actually update more than just the status. Maybe can make it more clear (something like "Update the details of an internship application at a specified index")

Below is a screenshot of the bug:

Image

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #156: [PE-D][Tester A] Bugfix: update command listing is repetitive and unclear
### Description
When updating fields, the sucessful update message is repetitive and unclear, refering to the entries as internship INDEX.

### Steps to Reproduce

1. Launch the application.

2. Add an application.

3. Update multiple fields of the applicaiton e.g. update 1 pay/10000 company/microsoft status/pending

4. Observe update message.
Updated internship 1 company to: Microsoft
Updated internship 1 pay to: 10000
Updated internship 1 status to: Offer

### Suggested Fix
Have one update message at the end that shows the previous application and how it has changed to the current one, for example.

Internship at 
Google, Software Engineer Intern, 17-09-2025, 100000, Pending 
is updated to
Microsoft, Software Engineer Intern, 17-09-2025, 10000, Offer

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by V1T0bh**
changelog:

1. fix matching index for find command, fixes #135
 
2. fix wrong description of update command in Help Command, fixes #153

3. fix incorrect update message -> shows field, index, new value, solves , fixes #134 

4. update command what if multiple, fixes #156 
*Output example:*
```
Internship at index 1 successfully updated:
Original:
  Google - Janitor | Deadline: 10-10-2025 | Pay: 100 | Status: Pending
Updated:
  Google - Janitor | Deadline: 10-10-2025 | Pay: 100 | Status: Rejected
```

5. ban time travellers, fixes #152 , #132 
*Note*: now shows only future deadlines. if no future deadline is found, shows past nearest deadline with OVERDUE note

**STATUS: Feel free to PUSH :)**

### CODE REVIEW

File: src/main/java/internity/core/InternshipList.java [hunk 1]
```diff
@@ -265,4 +265,53 @@ public static void setUsername(String username) {
...
+                    || (internship.getDeadline().compareTo(nearest.getDeadline()) < 0);
+            boolean isDeadlineInFuture = (Date.getToday().compareTo(internship.getDeadline()) <= 0);
+
+            if (isNearestDeadline && isDeadlineInFuture) {
+                nearest = internship;
+            }
+        }
+
+        // if no internships have future deadlines, get the nearest past deadline
+        if (nearest == null){
```
Comment (lukeai-tan) [inline src/main/java/internity/core/InternshipList.java]:
```suggestion
        if (nearest == null) {
```

**Review by lukeai-tan — APPROVED** [review]
Looks good to moi!
